[Events] Use old layout for non-live events and Add chat watcher count
christfellowshipchurch/web-app pull request #178
Opened 2020-10-09 15:44 UTC by rkdavidson

# Related Issue
- [**🏕 [Events] Remove schedule from Live event layout**](https://3.basecamp.com/3926363/buckets/17566548/todos/3094801989)
- [**🏕 [Events] Use existing layout for non-live events**](https://3.basecamp.com/3926363/buckets/17566548/todos/3076462962)
- [**🏕 [Chat] Show watcher count**](https://3.basecamp.com/3926363/buckets/17566548/todos/3100735047)

# Changes or Updates
- Cleans up component structure so the old Events layout is rendered with the new components for non-live events
- Pulls **Schedule** info out of side-panel, and puts it down by the description (for live events)
- Adds number of users currently watching

# Test Instructions
- Open an event that is not live locally _and_ on production site
  - I.e. http://local.christfellowship.church:3000/events/tune-in-online and https://christfellowship.church/events/tune-in-online
- 🔸 Verify the layouts closely match, across screen sizes (note: some typography tweaks were made within Schedule display)
- Open an event that is live
- 🔸 Verify:
  - The **Schedule** info is no longer in the side panel, but down by the description area
  - The number of users currently watching is displayed in the top right... log in as a different user in an Incognito window and refresh them to validate decrement/increment as connections change
  - Gut-check responsive layout sizes

# Screenshots

|Non-Live Event|Live Event|
|---|---|
|![2020-10-09 10 54 41](https://user-images.githubusercontent.com/1812955/95602112-73a08e80-0a22-11eb-9450-d4fe5d3ce2b5.gif)|![2020-10-09 11 40 17](https://user-images.githubusercontent.com/1812955/95603476-55d42900-0a24-11eb-9089-91a8be82a30c.gif)|
|![CleanShot 2020-10-09 at 10 54 20@2x](https://user-images.githubusercontent.com/1812955/95603446-49e86700-0a24-11eb-9fa0-aba2f6552198.jpg)|![CleanShot 2020-10-09 at 11 39 31@2x](https://user-images.githubusercontent.com/1812955/95603470-52d93880-0a24-11eb-983b-23d3932e27e8.jpg)|

|Watcher Count (recorded before design polish)|
|---|
|<img src="https://user-images.githubusercontent.com/1812955/95603499-5cfb3700-0a24-11eb-9498-d2c5bda1a82c.gif" width="480" />|

# Tests
- [ ] needed snapshots updated
- [ ] mobile tested
- [ ] latest update from master

2020-10-09 21:52 UTC, jordanwade requested changes

2020-10-09 21:56 UTC, jordanwade commented
@rkdavidson 
Looking good, just saw a handful of console logs and one issue with the the watch count.

2020-10-09 21:57 UTC, jordanwade commented
Also, just saw a small issue with an empty card on the `wake` event. Ignore if it isn't related to your changes.

![image](https://user-images.githubusercontent.com/2528817/95634870-829e3580-0a50-11eb-8ec1-3c5dd7363b8f.png)

2020-10-09 23:29 UTC, rkdavidson commented
Good catch on that Wake event, @jordanwade — not sure how to gracefully handle this, other than returning null so the whole description slots over to the left in its place.

This is some of the stuff we'll circle back with and fix scheduling overall for, so hopefully a temporary problem.

2020-10-09 23:29 UTC, rkdavidson commented on src/content-single/EventContentItem/components/EventSchedule.js
> +  console.groupCollapsed('[schedule] 📍 getScheduleByLocation()');
No, probably not anymore — meant to remove them but added back to triage issue earlier today. Will remove.

2020-10-12 14:51 UTC, jordanwade approved these changes

2020-10-13 14:26 UTC, rkdavidson commented on src/content-single/EventContentItem/components/CallsToAction.js
> +const CallsToAction = ({ eventTitle, items, hasEvents }) => {
Great catch, @jordanwade — the product requirements here are in flux/fuzzy, but to keep existing behavior, I updated the new `EventSchedule` to properly pass `hasEvents` down to conditionally show the **Get Started** subhead.

Insert spiel about how we'll imminently revisit this **Schedule** and **Calls to Action** portion, regardless 🙃.

Commit: 4445e5a

2020-10-13 15:08 UTC, rkdavidson commented on src/content-single/EventContentItem/components/EventChat.js
> +    } else if (
Great catch — updated in 11a5dd7 to count events related to _guests_ OR users other than me.

2020-10-13 15:13 UTC, rkdavidson commented
@jordanwade Responded to your feedback in a series of small commits, and addressed the empty schedule area on that Wake event by returning `null` if there are no events _and_ no calls to action — i.e. nothing to render.

2020-10-14 12:55 UTC, merged

2020-10-14 12:56 UTC, rkdavidson commented
@jordanwade I went ahead and merged this to minimize churn/conflicts with the **Stream XP** work.
I'm confident in the changes/fixes for the items you called out 🤞.