Stream xp
christfellowshipchurch/web-app pull request #180
Opened 2020-10-14 17:46 UTC by JSGraef

# Related Issue
- issue goes here

# Changes or Updates
- change 1
- change 2

# Tests
- [ ] needed snapshots updated
- [ ] mobile tested
- [ ] latest update from master

2020-10-20 20:10 UTC, jordanwade commented
@JSGraef I'm not sure if this issue is because the video is in a constant loading state, but anywhere I click on the video window toggles the theater mode. Is that to be expected? 
https://www.loom.com/share/fd0e7eac11d445da91d46c3b1413fad5?from_recorder=1

2020-10-20 20:14 UTC, JSGraef commented
@jordanwade good find, looking into it.

2020-10-20 20:16 UTC, jordanwade commented on src/ui/Media/Video.js
> +            paddingBottom: '2.1rem',
I'm not super experienced with the web-app, but it looks like they have a helper function you might be able to use here called `baseUnit` in the `theme.js`. I not sure how the other icons are aligned, so might not be helpful.

2020-10-20 20:27 UTC, JSGraef commented on src/ui/Media/Video.js
> +            paddingBottom: '2.1rem',
None would fully correspond with what is needed I don't think. I won't pretend this is the best way to achieve this padding, but it doesn't appear that the `baseUnit` would help me here.

2020-10-21 14:54 UTC, rkdavidson requested changes
Code looks great for this, love the `<TheaterModeProvider>` solution.
Now thinking I should use something similar-ish for Chat, to cleanup a big clunky `useEffect` there...

### Design/UI feedback

**Pointer Events on Video controls**
The `mouse hover` events are blocked by the new theater mode button container.
Related, it feels a bit awkward in the bottom center to me. WDYT about the top right corner instead?

|Hover not working|Hover works with `pointer-events: none`|
|---|---|
|![events blocked](https://user-images.githubusercontent.com/1812955/96735997-27424080-138a-11eb-8b42-ce539f682e82.gif)|![events good](https://user-images.githubusercontent.com/1812955/96735838-f9f59280-1389-11eb-88e1-1c11537d8dd2.gif)|

**Theater mode Icon**
Could we use a slightly transparent white instead of opaque gray for the icon fill?
And there's a little black triangle path for the TV antennae that may need a `fill="none"` or something? (Might only affect inactive state 🤔)

<img src="https://user-images.githubusercontent.com/1812955/96736673-d4b55400-138a-11eb-831b-39093891b02a.jpg" width="150" /> <img src="https://user-images.githubusercontent.com/1812955/96736921-17772c00-138b-11eb-8b1c-1e28cab7a684.png" width="176" />

**iPhone X Layout**
The layout has slightly off-centered padding horizontally, and a big gap below the video:
<img src="https://user-images.githubusercontent.com/1812955/96737318-88b6df00-138b-11eb-920b-5438bff0ea4a.jpg" width="275" />
The other major sizes like iPad portrait/landscape, iPad Pro portrait/landscape, etc look good 👍 .

2020-10-21 14:54 UTC, rkdavidson commented on src/hooks/useLocalStorage.js
> +  const keyPath = `${LS_PREFIX}:${itemKey}`;
I like this hook and the namespaced keys via `prefix`, but FYI there's already a couple local storage items in use that _may_ be worth considering.

The currently used keys are defined globally in [src/keys/index.js](https://github.com/christfellowshipchurch/web-app/blob/master/src/keys/index.js).
The `useAuth` hook reads/writes the user auth token via localStorage over in [src/auth/Provider.js](https://github.com/christfellowshipchurch/web-app/blob/master/src/auth/Provider.js).
The other place is to store users' preferred campus selection, used in [`<EventScheduleConnected>`](https://github.com/christfellowshipchurch/web-app/blob/master/src/content-single/EventContentItem/components/EventScheduleConnected.js#L19).

Not suggesting we have to do change anything, but pointing out in case there's a low effort way to consolidate/streamline somewhere that comes to mind.

2020-10-21 14:54 UTC, rkdavidson commented on src/providers/TheaterModeProvider.js
> +const TheaterModeProvider = ({ children }) => {
I love all this. Forgot about `useReducer`. For sure copying this in the future.
Sayonara, `redux`!

2020-10-21 14:54 UTC, rkdavidson commented on src/ui/Icons/index.js
> +  EnvelopeOpenDollar,
Thanks for cleaning the import/exports up in this file. 🙇‍♂️

2020-10-21 14:54 UTC, rkdavidson commented on src/ui/Media/Video.js
> +            paddingBottom: '2.1rem',
Chiming in late to say yes, the `theme` and `baseUnit` stuff is in a largely useless intermediate state right now.
My first goal was to mirror values in use from bootstrap today (i.e. the classes `p-2`, `mr-4`, etc).

That's why it's a silly key/value lookup instead of actual math.
This'll need a deeper look across the board in the future anyway so I'm not sweating arbitrary values like `2.1rem` here and there.

2020-10-21 18:47 UTC, JSGraef commented on src/hooks/useLocalStorage.js
> +  const keyPath = `${LS_PREFIX}:${itemKey}`;
Good callout about the key - I'll add it in there. Regarding the other localstorage usages, that would be a good F&I addition to tackle in another scope. They'll still continue to work, but it would be good to add prefixes to those items.

2020-10-21 19:37 UTC, JSGraef commented
@rkdavidson Updated everything you mentions, though I don't see that issue with iphoneX when I try it out. I would also imagine if on a phone they would prefer to use the app instead.

2020-10-21 20:13 UTC, jordanwade commented
@JSGraef you might know about this one already, but looks like theater mode icon is overlaying the mute/volume button now.
![image](https://user-images.githubusercontent.com/2528817/96777398-e78e4f80-13af-11eb-9603-7041bf046f5a.png)

2020-10-21 22:35 UTC, JSGraef commented
@jordanwade what are you viewing that on? I don't get the three dot option menu at all.

2020-10-22 14:29 UTC, jordanwade commented
> @jordanwade what are you viewing that on? I don't get the three dot option menu at all.

@JSGraef Chrome Version 86.0.4240.80
http://localhost:3000/events/check-in-test

![image](https://user-images.githubusercontent.com/2528817/96886245-042a9600-1449-11eb-9ae2-151a167f3d04.png)

2020-10-22 14:31 UTC, jordanwade commented
The three dot option is `picture and picture`.

2020-10-22 14:38 UTC, jordanwade commented
@JSGraef you could probably just add `disablePictureInPicture` on `<video>` as a quick fix.

2020-10-22 14:40 UTC, JSGraef commented
Huh, I'm two versions ahead on Chrome and two minors ahead on Catalina. I'll try your way.

2020-10-22 14:46 UTC, JSGraef commented
@jordanwade show up now?

2020-10-22 14:59 UTC, jordanwade commented
@JSGraef nope that fixed it 👍

2020-10-22 20:14 UTC, jordanwade commented
@rkdavidson @JSGraef do you think we need to put this behind a feature flag?

2020-10-23 14:38 UTC, rkdavidson commented
I can take another quick peak at this PR before merging, but it should be ready to go without a feature flag.
The events scope from last cycle is still only visible via the `sandbox` build config — i.e. **local** and the **beta** environments.

This Stream XP scope is essentially a UI enhancement of last cycle's events work, so I think we're all comfortable treating them as one "releasable" feature.

![image](https://user-images.githubusercontent.com/1812955/97008947-79619e00-1511-11eb-9550-d6923f61bd79.png)

2020-10-23 15:19 UTC, rkdavidson approved these changes
LGTM, nice fixes/changes this morning @JSGraef 👍

2020-10-23 15:19 UTC, merged